[package]
name = "day_01"
version = "0.1.0"
authors = ["Lukas Vollenweider <lukas@vollenweider.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
